export type RouteRegion =
  | "Andorra"
  | "Vall de Boí"
  | "Costa Brava"
  | "Costa Daurada"
  | "Barcelona"
  | "La Cerdanya"

export type RouteSport =
  | "Senderismo"
  | "Trail running"
  | "Bicicleta de carretera"
  | "Bicicleta de montaña"
  | "Esquí"
  | "Esquí de montaña"
  | "Raquetas de nieve"

export type RouteDifficulty = "Fácil" | "Moderada" | "Difícil"

export type RouteLibraryItem = {
  id: string
  coverImageUrl: string
  name: string
  tenantCount: number
  region: RouteRegion
  sport: RouteSport
  difficulty: RouteDifficulty
  isCircular: boolean
  isFamilyFriendly: boolean
  distanceKm: number
  elevationGainM: number
  durationMin: number
  author: string
}

export const ROUTE_REGIONS: RouteRegion[] = [
  "Andorra",
  "Vall de Boí",
  "Costa Brava",
  "Costa Daurada",
  "Barcelona",
  "La Cerdanya",
]

export const ROUTE_SPORTS: RouteSport[] = [
  "Senderismo",
  "Trail running",
  "Bicicleta de carretera",
  "Bicicleta de montaña",
  "Esquí",
  "Esquí de montaña",
  "Raquetas de nieve",
]

export const ROUTE_DIFFICULTIES: RouteDifficulty[] = ["Fácil", "Moderada", "Difícil"]

export const ROUTE_AUTHORS = [
  "Anton Òdena",
  "Marta Soler",
  "Jordi Roca",
  "Laia Casas",
  "Pau Valls",
  "Núria Mir",
  "Eric Costa",
  "Carla Vidal",
]

export const routeLibrarySeed: RouteLibraryItem[] = [
  {
    id: "route_001",
    coverImageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=320&q=80",
    name: "Circular Lagos de Tristaina",
    tenantCount: 8,
    region: "Andorra",
    sport: "Senderismo",
    difficulty: "Moderada",
    isCircular: true,
    isFamilyFriendly: false,
    distanceKm: 11.4,
    elevationGainM: 620,
    durationMin: 250,
    author: "Anton Òdena",
  },
  {
    id: "route_002",
    coverImageUrl: "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=320&q=80",
    name: "Paseo familiar Camí de Ronda",
    tenantCount: 5,
    region: "Costa Brava",
    sport: "Senderismo",
    difficulty: "Fácil",
    isCircular: false,
    isFamilyFriendly: true,
    distanceKm: 6.2,
    elevationGainM: 120,
    durationMin: 110,
    author: "Marta Soler",
  },
  {
    id: "route_003",
    coverImageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=320&q=80",
    name: "Serra de Collserola Trail",
    tenantCount: 6,
    region: "Barcelona",
    sport: "Trail running",
    difficulty: "Moderada",
    isCircular: true,
    isFamilyFriendly: false,
    distanceKm: 18.7,
    elevationGainM: 780,
    durationMin: 170,
    author: "Jordi Roca",
  },
  {
    id: "route_004",
    coverImageUrl: "https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?auto=format&fit=crop&w=320&q=80",
    name: "Port del Cantó Road",
    tenantCount: 3,
    region: "La Cerdanya",
    sport: "Bicicleta de carretera",
    difficulty: "Difícil",
    isCircular: false,
    isFamilyFriendly: false,
    distanceKm: 95.4,
    elevationGainM: 2100,
    durationMin: 360,
    author: "Pau Valls",
  },
  {
    id: "route_005",
    coverImageUrl: "https://images.unsplash.com/photo-1533460004989-cef01064af7e?auto=format&fit=crop&w=320&q=80",
    name: "Vía Verde del Ebro",
    tenantCount: 4,
    region: "Costa Daurada",
    sport: "Bicicleta de montaña",
    difficulty: "Fácil",
    isCircular: false,
    isFamilyFriendly: true,
    distanceKm: 32.1,
    elevationGainM: 410,
    durationMin: 210,
    author: "Laia Casas",
  },
  {
    id: "route_006",
    coverImageUrl: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=320&q=80",
    name: "Ascenso al Comapedrosa",
    tenantCount: 7,
    region: "Andorra",
    sport: "Senderismo",
    difficulty: "Difícil",
    isCircular: false,
    isFamilyFriendly: false,
    distanceKm: 14.3,
    elevationGainM: 1350,
    durationMin: 410,
    author: "Núria Mir",
  },
  {
    id: "route_007",
    coverImageUrl: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=320&q=80",
    name: "Bosc de Gerdar Circular",
    tenantCount: 5,
    region: "Vall de Boí",
    sport: "Raquetas de nieve",
    difficulty: "Moderada",
    isCircular: true,
    isFamilyFriendly: true,
    distanceKm: 7.8,
    elevationGainM: 290,
    durationMin: 145,
    author: "Eric Costa",
  },
  {
    id: "route_008",
    coverImageUrl: "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=320&q=80",
    name: "Ruta Alpina Vallter",
    tenantCount: 2,
    region: "La Cerdanya",
    sport: "Esquí de montaña",
    difficulty: "Difícil",
    isCircular: true,
    isFamilyFriendly: false,
    distanceKm: 12.6,
    elevationGainM: 980,
    durationMin: 300,
    author: "Carla Vidal",
  },
  {
    id: "route_009",
    coverImageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=320&q=80",
    name: "Vall de Boí Clásica",
    tenantCount: 9,
    region: "Vall de Boí",
    sport: "Senderismo",
    difficulty: "Fácil",
    isCircular: true,
    isFamilyFriendly: true,
    distanceKm: 5.4,
    elevationGainM: 140,
    durationMin: 90,
    author: "Marta Soler",
  },
  {
    id: "route_010",
    coverImageUrl: "https://images.unsplash.com/photo-1533460004989-cef01064af7e?auto=format&fit=crop&w=320&q=80",
    name: "Ruta de los Acantilados",
    tenantCount: 6,
    region: "Costa Brava",
    sport: "Trail running",
    difficulty: "Moderada",
    isCircular: false,
    isFamilyFriendly: false,
    distanceKm: 16.2,
    elevationGainM: 510,
    durationMin: 180,
    author: "Anton Òdena",
  },
  {
    id: "route_011",
    coverImageUrl: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=320&q=80",
    name: "Refugios de Ordino",
    tenantCount: 7,
    region: "Andorra",
    sport: "Esquí",
    difficulty: "Moderada",
    isCircular: true,
    isFamilyFriendly: false,
    distanceKm: 21.7,
    elevationGainM: 1100,
    durationMin: 340,
    author: "Jordi Roca",
  },
  {
    id: "route_012",
    coverImageUrl: "https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?auto=format&fit=crop&w=320&q=80",
    name: "Cerdanya Gravel Tour",
    tenantCount: 4,
    region: "La Cerdanya",
    sport: "Bicicleta de montaña",
    difficulty: "Moderada",
    isCircular: true,
    isFamilyFriendly: false,
    distanceKm: 58.3,
    elevationGainM: 1280,
    durationMin: 320,
    author: "Pau Valls",
  },
  {
    id: "route_013",
    coverImageUrl: "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=320&q=80",
    name: "Anella Olímpica BCN",
    tenantCount: 8,
    region: "Barcelona",
    sport: "Bicicleta de carretera",
    difficulty: "Fácil",
    isCircular: true,
    isFamilyFriendly: true,
    distanceKm: 24.8,
    elevationGainM: 260,
    durationMin: 130,
    author: "Laia Casas",
  },
  {
    id: "route_014",
    coverImageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=320&q=80",
    name: "Costa Daurada Sunset Run",
    tenantCount: 3,
    region: "Costa Daurada",
    sport: "Trail running",
    difficulty: "Fácil",
    isCircular: false,
    isFamilyFriendly: true,
    distanceKm: 9.9,
    elevationGainM: 180,
    durationMin: 95,
    author: "Núria Mir",
  },
  {
    id: "route_015",
    coverImageUrl: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=320&q=80",
    name: "Skimo Coma Pedrosa",
    tenantCount: 2,
    region: "Andorra",
    sport: "Esquí de montaña",
    difficulty: "Difícil",
    isCircular: false,
    isFamilyFriendly: false,
    distanceKm: 15.1,
    elevationGainM: 1450,
    durationMin: 430,
    author: "Carla Vidal",
  },
  {
    id: "route_016",
    coverImageUrl: "https://images.unsplash.com/photo-1533460004989-cef01064af7e?auto=format&fit=crop&w=320&q=80",
    name: "Bosques de la Molina",
    tenantCount: 5,
    region: "La Cerdanya",
    sport: "Raquetas de nieve",
    difficulty: "Moderada",
    isCircular: true,
    isFamilyFriendly: true,
    distanceKm: 8.5,
    elevationGainM: 330,
    durationMin: 160,
    author: "Eric Costa",
  },
  {
    id: "route_017",
    coverImageUrl: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=320&q=80",
    name: "Vuelta al Pedraforca",
    tenantCount: 6,
    region: "Vall de Boí",
    sport: "Senderismo",
    difficulty: "Difícil",
    isCircular: true,
    isFamilyFriendly: false,
    distanceKm: 13.2,
    elevationGainM: 1040,
    durationMin: 360,
    author: "Anton Òdena",
  },
  {
    id: "route_018",
    coverImageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=320&q=80",
    name: "Coll de la Creueta Road",
    tenantCount: 3,
    region: "La Cerdanya",
    sport: "Bicicleta de carretera",
    difficulty: "Difícil",
    isCircular: false,
    isFamilyFriendly: false,
    distanceKm: 87.6,
    elevationGainM: 1950,
    durationMin: 330,
    author: "Jordi Roca",
  },
  {
    id: "route_019",
    coverImageUrl: "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=320&q=80",
    name: "Ruta familiar de Encamp",
    tenantCount: 7,
    region: "Andorra",
    sport: "Senderismo",
    difficulty: "Fácil",
    isCircular: true,
    isFamilyFriendly: true,
    distanceKm: 4.7,
    elevationGainM: 90,
    durationMin: 70,
    author: "Marta Soler",
  },
  {
    id: "route_020",
    coverImageUrl: "https://images.unsplash.com/photo-1533460004989-cef01064af7e?auto=format&fit=crop&w=320&q=80",
    name: "BTT Litoral Costa Brava",
    tenantCount: 4,
    region: "Costa Brava",
    sport: "Bicicleta de montaña",
    difficulty: "Moderada",
    isCircular: false,
    isFamilyFriendly: false,
    distanceKm: 41.2,
    elevationGainM: 860,
    durationMin: 245,
    author: "Pau Valls",
  },
]

export function getRouteById(routeId: string) {
  return routeLibrarySeed.find((route) => route.id === routeId)
}
